### ISSUE TITLE
Crash after purchase (watchOS)

### ISSUE THREAD

**Issue by vincentneo** [RevenueCat/purchases-ios#2338]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-ios/blob/main/Contributing/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-ios/issues)

**Describe the bug**
A clear and concise description of what the bug is. The more detail you can provide the faster our team will be able to triage and resolve the issue. **Do not remove any of the steps from the template below. If a step is not applicable to your issue, please leave that step empty.**

1. Environment
   1. Platform: Apple Watch
   2. SDK version: 4.17.7
   3. StoreKit 2 (_disabled with `useStoreKit2IfEnabled(false)`_) (Y/N): did not use `useStoreKit2IfEnabled` function
   4. OS version: watchOS 9.3.1
   5. Xcode version: Xcode 14.2
   6. How widespread is the issue. Percentage of devices affected. Tested on my device
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue

Slightly not following the template because there's 2 parts to this issue, also because I'm an idiot.

#### Part 1 
I observed this crash before (below is replicated today), before release of app:
Not sure how you get a crash log out of Xcode but here's a screenshot that maybe helps. (Note that this is RevenueCat 4.17.7, unmodified)
<img width="1900" alt="Screenshot 2023-03-15 at 12 04 01 PM" src="https://user-images.githubusercontent.com/23420208/225204619-b6deae37-5cea-4858-8113-263cbf107071.png">

The last few revenue cat console log:
```
2023-03-15 12:01:38.620022+0800 Pigeon WatchKit Extension[385:11853] [Purchases] - INFO: 💰 Purchasing Product 'pigeon.fullaccess.1year' from package in Offering 'full.access'
2023-03-15 12:01:38.622930+0800 Pigeon WatchKit Extension[385:11793] [Purchases] - DEBUG: ℹ️ StoreKit1Wrapper (0x16eeae40) updatedTransaction: pigeon.fullaccess.1year 0
2023-03-15 12:02:42.757877+0800 Pigeon WatchKit Extension[385:11853] [Purchases] - DEBUG: ℹ️ StoreKit1Wrapper (0x16eeae40) updatedTransaction: pigeon.fullaccess.1year 2000000296477008 2000000293494300 1
(lldb) 
```

Smart alec me thought, eh, must be a arm64_32 thing where `Int` is 32 bits. I'm just gonna make a fork and comment things out: https://github.com/vincentneo/purchases-ios/commit/2d9ef0cf61c880891a662b23ff4c8ec4f054873a

Things work fine for sandbox with that change, up until:
![incoming-3A37AC3B-C9CB-4D7F-B337-B829CD13A40F](https://user-images.githubusercontent.com/23420208/225206243-81d667bb-0f46-491f-9201-518a0879ff01.PNG)
But I thought, "must be a sandbox thing, with a StoreKit Configuration file, simulator works perfectly, so it be alright."

#### Part 2
Fast forward a few days later, the app is on the store. I downloaded and purchased the subscription to test, and it crashed right after the Apple's "Your purchase was successful." message. Relaunched it, and now it crashed on launch, and there I was, in full remorse. I quickly grabbed the .ips file from my phone, and symbolicate it in Xcode.

(Again, I don't know how you export a symbolicated ips but this screenshot probably helps) Note that this is running on my fork, which is based on `main` branch, slightly newer than 4.17.7.
<img width="1900" alt="Screenshot 2023-03-15 at 12 35 29 PM" src="https://user-images.githubusercontent.com/23420208/225207695-759f0114-48ce-46df-974a-208830e39deb.png">

With the nature of both crash seemingly related, both parts are in the same issue.

I apologise for not opening an issue earlier, but please help!

**Comment by RCGitBot** [comment]
👀 [SDKONCALL-237] We've just linked this issue to our internal tracker and notified the team. Thank you for reporting, we're checking this out!

**Comment by aboedo** [comment]
@vincentneo thanks for reporting and for all the details! The screenshots should be more than good enough for us to take a look 💪

**Comment by vincentneo** [comment]
By the way are there any options to temporarily disable receipt validation? 

For now I removed all the offerings in RevenueCat so at least no one gets to buy anything.
Though, I am afraid if there's anyone that attempted a purchase before I did that, so if there is such option, I could quickly whip up a minor release stopping the app from crashing on launch.

**Comment by NachoSoto** [comment]
Looking into this right now.

To confirm that this is indeed related to 32-bit watchOS devices, can you tell us which Apple Watch device you're testing with?

**Comment by NachoSoto** [comment]
Actually I can confirm this is not working on 32 bits. We'll get it fixed.

**Comment by vincentneo** [comment]
> Looking into this right now.
> 
> To confirm that this is indeed related to 32-bit watchOS devices, can you tell us which Apple Watch device you're testing with?

I’m using Apple Watch Series 7. The thing with 64 bit Apple Watches are that they are all kinda weird.
According to https://twitter.com/KhaosT/status/1039990586793648128?lang=en, its using 32 bit pointers still, despite the 64 bit architecture.

I guess it’s safe to assume all current Apple Watches would face this issue.

**Comment by NachoSoto** [comment]
It's unfortunate that `watchOS` simulators do use 64 bits though.

**Comment by vincentneo** [comment]
> It's unfortunate that `watchOS` simulators do use 64 bits though.

Yup.
In my opinion, Apple Watch is the hardest Apple platform to create apps for. 
Just had a weird SwiftUI crash which didn’t happen on the simulator too.

**Comment by NachoSoto** [comment]
And I'm currently unable to run tests on my Apple Watch. I can run an app, but Xcode 14.0 isn't seeing the watch when trying to run a test target...

**Comment by vincentneo** [comment]
Ah yes, Apple Watch connection issues with Xcode is always common, frustrating and problematic.

**Comment by NachoSoto** [comment]
Thanks a lot for the report! As you saw, the fix for this is out already :)

**Comment by vincentneo** [comment]
@NachoSoto yes, thank you! I’ve already prepared an update for my app with the fix, now in review!
