### ISSUE TITLE
Update all String files to use enum cases

### ISSUE THREAD

**Issue by aboedo** [RevenueCat/purchases-ios#819]
We're currently storing all logging strings as `static let`. 
This has the unfortunate side-effect of eagerly loading them all into memory. 

In addition, formatting them isn't very type-safe, and is difficult to do, because when using the strings, you don't know what each parameter does, in which order. 

We can improve upon this by transforming them into enum cases with labels. 

This means we can move from this syntax: 
```swift
Logger.info(String(format: Strings.whatever.purchasing_product, productId))
```

into this one: 

```swift
Logger.info(Strings.whatever.purchasing_product(productIdentifier: productId))
```

which gets a lot better when there are multiple parameters. 

Once all files have been updated, we can remove redundant methods in `Logging.swift` that take in `String`, since we'll only be passing in `CustomStringConvertible` types. 

- [x] `AttributionStrings` #816 
- [x] `CodableStrings` #818 
- [x] `ConfigureStrings` #817 
- [x] `IdentityStrings` #817 
- [x] `NetworkStrings` - assigned to @juanpe #833
- [x] `OfferingStrings` - assigned to @juanpe #833 
- [x] `PurchaserInfoStrings` - assigned to @juanpe #840 
- [x] `PurchaseStrings` - assigned to @juanpe #840 
- [x] `ReceiptStrings` - assigned to @aboedo https://github.com/RevenueCat/purchases-ios/pull/835
- [x] `RestoreStrings` - assigned to @aboedo https://github.com/RevenueCat/purchases-ios/pull/836
- [x] remove extra methods in Logging.swift - assigned to @aboedo #842

**Comment by Juanpe** [comment]
Hi @aboedo 👋🏼  
Are `PurchaserInfoStrings` and `PurchaseStrings` still not assigned? 🙂

**Comment by aboedo** [comment]
not yet! feel free to take them!
